import { Router } from "express";
import express from "express";
import authRouter from "./auth.router.js";
import usersRouter from "./user.router.js";
import teamRoute from "./team.router.js";
import playerRouter from "./player.router.js";
const router = express.Router();
router.use("/auth", authRouter);
router.use("/user", usersRouter);
router.use("/team",teamRoute);
router.use("/player",playerRouter);
export default router;
